### PR TITLE
Issue #3: Create the Home screen & Issue #5: Create Sign Up/Login Flow component screens

### LINKED ISSUE #3: Create the Home screen

### LINKED ISSUE #5: Create Sign Up/Login Flow component screens

### PR DESCRIPTION
**Pull request by SincerelyBrittany**
Created a home screen with two links that open up a signup/login form.

### CODE REVIEW

**Comment by blobbyblobfish** [comment]
@SincerelyBrittany I'm reviewing the code right now. Do you know if the <Form.Control> component updates the form input's values and the component state? Typically in React the pattern is to use controlled components. Here's some more information about controlled components: [React docs](https://reactjs.org/docs/forms.html), [Medium article](https://medium.com/byte-sized-react/controlled-forms-in-react-68e59362a119). I'm not familiar with the <Form.Control> component and when I looked at [this example of React-Bootstrap <Form.Control>](https://react-bootstrap-v3.netlify.app/components/forms/), they show the component as having a value prop that is set to this.state.value with an onChange that updates this.state. I am uncertain but it seems like you may need to initialize a state object in Login.js and Signup.js and set email, password, name, etc. as empty strings. You'd then set onChange on the inputs to a handleChange function like so:

```
handleChange = (e) => {
    this.setState({
      [e.target.name]: e.target.value
    })
  }
```
@shivaylamba Do we want to include the ios build folder when we make commits?

**Comment by SincerelyBrittany** [comment]
Hi @shivaylamba and @blobbyblobfish, I removed the ios files.

**Comment by SincerelyBrittany** [comment]
@blobbyblobfish & @shivaylamba I removed the <Form.Control>.

**Comment by blobbyblobfish** [comment]
@SincerelyBrittany @shivaylamba What are your opinions on the controlled component comment that I wrote above?

**Review by shivaylamba — APPROVED** [review]
LGTM

**Pull request merged**
